"""
常量定义模块
包含文件类型映射、过滤规则等常量配置
"""

from pathlib import Path

DEFAULT_EXCLUDE_DIRS = [
    '__pycache__',
    '.git',
    '.svn',
    '.hg',
    'node_modules',
    'bower_components',
    'dist',
    'build',
    'out',
    '.idea',
    '.vscode',
    '.vs',
    'venv',
    '.venv',
    'env',
    '.env',
    'ENV',
    '.pytest_cache',
    '.tox',
    '.mypy_cache',
    '.ruff_cache',
    '.coverage',
    'htmlcov',
    '.eggs',
    '*.egg-info',
    '.DS_Store',
    'Thumbs.db',
    '*.pyc',
    '*.pyo',
    '*.so',
    '*.dll',
    '*.dylib',
    '.gradle',
    'target',
    'bin',
    'obj',
]

DEFAULT_EXCLUDE_FILES = [
    '*.pyc',
    '*.pyo',
    '*.so',
    '*.dll',
    '*.dylib',
    '*.class',
    '*.o',
    '*.obj',
    '.DS_Store',
    'Thumbs.db',
]

FILE_TYPE_MAPPING = {
    '.py': 'Python',
    '.pyw': 'Python',
    '.js': 'JavaScript',
    '.jsx': 'JavaScript React',
    '.ts': 'TypeScript',
    '.tsx': 'TypeScript React',
    '.java': 'Java',
    '.kt': 'Kotlin',
    '.go': 'Go',
    '.rs': 'Rust',
    '.rb': 'Ruby',
    '.php': 'PHP',
    '.c': 'C',
    '.cpp': 'C++',
    '.cc': 'C++',
    '.cxx': 'C++',
    '.h': 'C Header',
    '.hpp': 'C++ Header',
    '.cs': 'C#',
    '.swift': 'Swift',
    '.m': 'Objective-C',
    '.mm': 'Objective-C++',
    '.vue': 'Vue',
    '.svelte': 'Svelte',
    '.html': 'HTML',
    '.htm': 'HTML',
    '.css': 'CSS',
    '.scss': 'SCSS',
    '.sass': 'Sass',
    '.less': 'Less',
    '.json': 'JSON',
    '.xml': 'XML',
    '.yaml': 'YAML',
    '.yml': 'YAML',
    '.toml': 'TOML',
    '.md': 'Markdown',
    '.markdown': 'Markdown',
    '.txt': 'Text',
    '.sql': 'SQL',
    '.sh': 'Shell',
    '.bash': 'Bash',
    '.zsh': 'Zsh',
    '.ps1': 'PowerShell',
    '.bat': 'Batch',
    '.cmd': 'Batch',
    '.r': 'R',
    '.lua': 'Lua',
    '.pl': 'Perl',
    '.scala': 'Scala',
    '.groovy': 'Groovy',
    '.gradle': 'Gradle',
}

CONFIG_FILES = {
    'requirements.txt': 'Python',
    'pyproject.toml': 'Python',
    'setup.py': 'Python',
    'Pipfile': 'Python',
    'poetry.lock': 'Python',
    'package.json': 'JavaScript',
    'package-lock.json': 'JavaScript',
    'tsconfig.json': 'TypeScript',
    'vite.config.js': 'Vite',
    'vite.config.ts': 'Vite',
    'webpack.config.js': 'Webpack',
    '.babelrc': 'Babel',
    'pom.xml': 'Java Maven',
    'build.gradle': 'Java Gradle',
    'build.gradle.kts': 'Kotlin Gradle',
    'go.mod': 'Go',
    'go.sum': 'Go',
    'Gemfile': 'Ruby',
    'Gemfile.lock': 'Ruby',
    'composer.json': 'PHP',
    'Cargo.toml': 'Rust',
    'Cargo.lock': 'Rust',
    'CMakeLists.txt': 'C++ CMake',
    'Makefile': 'Make',
    'Dockerfile': 'Docker',
    'docker-compose.yml': 'Docker Compose',
    'docker-compose.yaml': 'Docker Compose',
    '.env.example': 'Environment',
    '.eslintrc': 'ESLint',
    '.eslintrc.js': 'ESLint',
    '.eslintrc.json': 'ESLint',
    '.prettierrc': 'Prettier',
    '.prettierrc.js': 'Prettier',
    '.prettierrc.json': 'Prettier',
}

FOLDER_NAME_PATTERNS = {
    'src': '源代码目录',
    'source': '源代码目录',
    'sources': '源代码目录',
    'app': '应用程序主目录',
    'lib': '库文件目录',
    'libs': '库文件目录',
    'libraries': '库文件目录',
    'utils': '工具函数库',
    'utilities': '工具函数库',
    'helpers': '辅助函数',
    'common': '公共模块',
    'core': '核心模块',
    'base': '基础模块',
    'components': '组件库',
    'widgets': '小部件组件',
    'containers': '容器组件',
    'layouts': '布局组件',
    'pages': '页面组件',
    'views': '视图组件',
    'screens': '屏幕组件',
    'modules': '功能模块',
    'features': '功能模块',
    'controllers': '控制器层',
    'services': '业务逻辑服务',
    'models': '数据模型',
    'schemas': '数据模式',
    'entities': '实体类',
    'repositories': '数据仓库层',
    'dal': '数据访问层',
    'middleware': '中间件',
    'interceptors': '拦截器',
    'filters': '过滤器',
    'plugins': '插件',
    'extensions': '扩展',
    'integrations': '集成模块',
    'tests': '测试代码',
    'test': '测试代码',
    '__tests__': '测试代码',
    'spec': '测试代码',
    'specs': '测试代码',
    'testing': '测试代码',
    'docs': '文档资料',
    'documentation': '文档资料',
    'doc': '文档资料',
    'api': 'API 接口',
    'apis': 'API 接口',
    'endpoints': 'API 端点',
    'routes': '路由配置',
    'config': '配置文件',
    'configs': '配置文件',
    'configuration': '配置文件',
    'settings': '设置文件',
    'assets': '静态资源',
    'static': '静态文件',
    'public': '公共资源',
    'resources': '资源文件',
    'data': '数据文件',
    'files': '数据文件',
    'images': '图片资源',
    'img': '图片资源',
    'icons': '图标资源',
    'fonts': '字体资源',
    'styles': '样式文件',
    'css': '样式文件',
    'scss': 'SCSS 样式',
    'themes': '主题文件',
    'locales': '本地化文件',
    'i18n': '国际化文件',
    'translations': '翻译文件',
    'scripts': '脚本文件',
    'tools': '工具脚本',
    'bin': '可执行文件',
    'scripts': '构建脚本',
    'migrations': '数据库迁移',
    'seeds': '数据种子',
    'fixtures': '测试数据',
    'examples': '示例代码',
    'samples': '示例代码',
    'demo': '演示代码',
    'demos': '演示代码',
    'temp': '临时文件',
    'tmp': '临时文件',
    'cache': '缓存文件',
    'logs': '日志文件',
    'build': '构建输出',
    'dist': '分发版本',
    'output': '输出目录',
    'coverage': '测试覆盖率报告',
    '.github': 'GitHub 配置',
    '.gitlab-ci.yml': 'GitLab CI',
    '.travis.yml': 'Travis CI',
    'jenkins': 'Jenkins 配置',
}

PYTHON_SPECIFIC_PATTERNS = {
    'migrations': '数据库迁移文件（Django/Flask）',
    'management': 'Django 管理命令',
    'management/commands': 'Django 自定义命令',
    'commands': '命令行工具',
    'cli': '命令行接口',
}

JS_FRAMEWORK_INDICATORS = {
    'react': 'React',
    'vue': 'Vue',
    'angular': 'Angular',
    'next': 'Next.js',
    'nuxt': 'Nuxt.js',
    'gatsby': 'Gatsby',
    'svelte': 'Svelte',
    'ember': 'Ember.js',
    'backbone': 'Backbone.js',
    'express': 'Express.js',
    'fastify': 'Fastify',
    'koa': 'Koa.js',
    'nest': 'NestJS',
    'mongoose': 'Mongoose',
    'sequelize': 'Sequelize',
    'prisma': 'Prisma',
    'axios': 'HTTP 客户端',
    'fetch': 'HTTP 请求',
    'socket.io': 'WebSocket',
    'redux': 'Redux',
    'mobx': 'MobX',
    'zustand': 'Zustand',
    'vuex': 'Vuex',
    'pinia': 'Pinia',
    'tailwind': 'Tailwind CSS',
    'antd': 'Ant Design',
    'material-ui': 'Material UI',
    'chakra': 'Chakra UI',
}

PYTHON_FRAMEWORK_INDICATORS = {
    'django': 'Django',
    'flask': 'Flask',
    'fastapi': 'FastAPI',
    'bottle': 'Bottle',
    'pyramid': 'Pyramid',
    'tornado': 'Tornado',
    'sanic': 'Sanic',
    'starlette': 'Starlette',
    'pydantic': 'Pydantic',
    'sqlalchemy': 'SQLAlchemy',
    'alembic': 'Alembic',
    'celery': 'Celery',
    'rq': 'Redis Queue',
    'dramatiq': 'Dramatiq',
    'requests': 'Requests',
    'aiohttp': 'aiohttp',
    'httpx': 'HTTPX',
    'pandas': 'Pandas',
    'numpy': 'NumPy',
    'matplotlib': 'Matplotlib',
    'seaborn': 'Seaborn',
    'sklearn': 'Scikit-learn',
    'tensorflow': 'TensorFlow',
    'torch': 'PyTorch',
    'keras': 'Keras',
    'pytest': 'Pytest',
    'unittest': 'Unittest',
    'coverage': 'Coverage',
    'black': 'Black',
    'ruff': 'Ruff',
    'mypy': 'Mypy',
    'pylint': 'Pylint',
    'flake8': 'Flake8',
    'isort': 'isort',
}

DEFAULT_OUTPUT_FILENAME = 'PROJECT_BLUEPRINT.md'

MAX_DEPTH = 10

MAX_FILES_PER_FOLDER = 100

MAX_FILE_SIZE_FOR_ANALYSIS = 1024 * 1024

DEFAULT_SCAN_DEPTH = 3
